import {
  ArrowRight,
  Code,
  Github,
  ExternalLink,
  TrendingUp,
  Bolt,
  LayoutGrid,
  Layers,
  Database,
  ShieldCheck,
  Accessibility,
  Gauge,
  Sparkles,
  Braces,
  Component,
  Wind,
  Award,
  ScalingIcon,
  ArrowUp,
  ArrowDown,
  MonitorSmartphone,
  Cloud,
  Mail,
  Calendar,
} from "lucide-react";

export const ICONS = {
  arrow_forward: ArrowRight,
  code_blocks: Code,
  github: Github,
  open_in_new: ExternalLink,
  trending_up: TrendingUp,
  bolt: Bolt,
  view_quilt: LayoutGrid,
  layers: Layers,
  database: Database,
  verified_user: ShieldCheck,
  accessibility: Accessibility,
  speed: Gauge,
  sparkle: Sparkles,
  braces: Braces,
  component: Component,
  wind: Wind,
  award: Award,
  scaling: ScalingIcon,
  arrow_up: ArrowUp,
  arrow_down: ArrowDown,
  monitor_smartphone: MonitorSmartphone,
  cloud: Cloud,
  mail: Mail,
  calendar: Calendar,
};

export type IconName = keyof typeof ICONS;
